import Head from "next/head";
import { useAuth } from "../lib/auth";
import styles from "../styles/Home.module.css";

export default function Home() {
  const auth = useAuth();
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Feedback</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="title">Feedback</h1>
        <button onClick={(e) => auth.signinWhitGithub()}>Sign in</button>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
